### ISSUE TITLE
Visual Studio 2019 Support

### ISSUE THREAD

**Issue by MoienTajik** [ins0mniaque/ILSupport#22]
Hello, are there any plans for Visual Studio 2019 support?

**Comment by ins0mniaque** [comment]
No release date yet, but as soon as I have the time to install Visual Studio 2019, I will add support for it.

**Comment by furesoft** [comment]
please upgrade to vs2019

**Comment by ins0mniaque** [comment]
IL Support 2.5 with Visual Studio 2019 support has been released.

**Comment by furesoft** [comment]
vsix cant be downloaded:
The specified account does not exist. RequestId:9a422fba-001e-0068-4ed6-7abefa000000 Time:2019-10-04T17:10:16.2066100Z

**Comment by ins0mniaque** [comment]
Not sure what could be causing this. Directly downloading the vsix or updating through Visual Studio Extension Manager (2017 and 2019) works for me.

Link to download: https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ins0mniaque/vsextensions/ILSupport/2.5/vspackage

**Comment by furesoft** [comment]
directly downloading the vsix causes the problem

**Comment by ins0mniaque** [comment]
I tried from multiple locations and computers, and the direct download link works for me.

https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ins0mniaque/vsextensions/ILSupport/2.5/vspackage

For now, I'm closing this issue, since the download problem is not related to supporting Visual Studio 2019.

If the issue of downloading the vsix persists, please open a new issue.
